name: YouTube Webhook Script

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering from Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Action to checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Action to set up Python
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-api-python-client  # Example dependencies

      - name: Execute Python script
        run: python main.py  # Replace with the command to run your Python script

      env:  # Environment variables for your script (replace with your own)
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
